### ISSUE TITLE
Add backup constraint raising AttributeError

### ISSUE THREAD

**Issue by gegen07** [erinrolson/spopt#1]
@erinrolson  I think for statement should be ident inside if, and the else of LOC 402 will be for the if clause and not for the for statements. 

https://github.com/erinrolson/spopt/blob/c852dcc1faffd9e6b7cda71d2ecbdfde89016e52/spopt/locate/coverage.py#L388-L405

**Comment by erinrolson** [comment]
You're correct. Thank you!
