### ISSUE TITLE
self.AssertRaises(RuntimeError) for LSCPB testing

### ISSUE THREAD

**Issue by erinrolson** [erinrolson/spopt#2]
The tests listed below are failing, but are producing a RuntimeError as desired. I think this is because when the LSCPB object fails it is because LSCP is infeasible, thus the error is produced from the LSCP object not the LSCPB object. How can we get these tests to pass?

FAILED spopt/tests/test_lscpb.py::TestRealWorldLocate::test_infeasibility_lscpb_from_geodataframe - RuntimeError: Mode...
FAILED spopt/tests/test_lscpb.py::TestErrorsWarnings::test_warning_lscpb_demand_geodataframe - RuntimeError: Model is ...
FAILED spopt/tests/test_lscpb.py::TestErrorsWarnings::test_warning_lscpb_facility_geodataframe - RuntimeError: Model i...
FAILED spopt/tests/test_lscpb.py::TestRealWorldLocate::test_infeasibility_lscpb_from_cost_matrix - RuntimeError: Model...

**Comment by gegen07** [comment]
@erinrolson Gotcha!!!

As LSCP-B depends on LSCP, if LSCP is infeasible consequently LSCPB is infeasible. So you should enclose the `LSCP.from_cost_matrix` method with the `with-statement`.

You can do:
From : 
```
    def test_infeasibility_lscpb_from_cost_matrix(self):
        lscpb = LSCPB.from_cost_matrix(
            self.cost_matrix, 20, pulp.PULP_CBC_CMD(msg=False)
        )
        with self.assertRaises(RuntimeError):  # ask someone about this
            lscpb.solve(pulp.PULP_CBC_CMD(msg=False))
```

To:  

```
    def test_infeasibility_lscpb_from_cost_matrix(self):
        with self.assertRaises(RuntimeError):  # ask someone about this 
             lscpb = LSCPB.from_cost_matrix(
                 self.cost_matrix, 20, pulp.PULP_CBC_CMD(msg=False)
            )
            lscpb.solve(pulp.PULP_CBC_CMD(msg=False))```

**Comment by erinrolson** [comment]
Ah, duh! Thanks!
