### ISSUE TITLE
self.AssertWarns(Warning) LSCPB testing

### ISSUE THREAD

**Issue by erinrolson** [erinrolson/spopt#3]
I modified the following functions to account for LSCP solving producing a RuntimeError. Is this an appropriate way to handle the LSCP error and still test the warnings? These tests are passing with my modifications.

   def test_warning_lscpb_facility_geodataframe(self):
        with self.assertWarns(Warning):
            with self.assertRaises(RuntimeError):
                dummy_class = LSCPB.from_geodataframe(
                    self.gdf_dem,
                    self.gdf_fac,
                    "geometry",
                    "geometry",
                    10,
                    pulp.PULP_CBC_CMD(msg=False),
                )

    def test_warning_lscpb_demand_geodataframe(self):
        with self.assertWarns(Warning):
            with self.assertRaises(RuntimeError):
                dummy_class = LSCPB.from_geodataframe(
                    self.gdf_dem_buffered,
                    self.gdf_fac,
                    "geometry",
                    "geometry",
                    10,
                    pulp.PULP_CBC_CMD(msg=False),
                )

**Comment by gegen07** [comment]
When we are doing unit testing, it's supposed to test only a single feature. So, to test this warning, I would change the model to a feasible model and just test the warning, since I think a runtime error is already covered by another test.

**Comment by erinrolson** [comment]
Thanks!
